apiVersion: v1
kind: Secret
metadata: 
  name: postgres-secrets
type: Opaque
data: 
  # DB_USER: postgres
  DB_USER: cG9zdGdyZXM=
  # DB_PASSWORD: EstoEsUnPasswordSecreto
  DB_PASSWORD: RXN0b0VzVW5QYXNzd29yZFNlY3JldG8=
